spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        default_schema: whitepappers
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 100
        order_inserts: true
        metadata_builder_contributor: alekseybykov.portfolio.whitepappers.config.database.SqlFunctionsMetadataBuilderContributor
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1

server:
  port: 8080
  servlet:
    context-path: /whitepappers/api/v1

fileservice:
  file:
    max-size: 52428800
  move-delay: 10000
  storage:
    local:
      path: whitepappers_local_files
    minio:
      bucket: whitepappers
      host: http://127.0.0.1:9000
      login: whitepappersminio
      password: whitepappersminio
