spring:
  jpa:
    database: postgresql
    open-in-view: true
    generate-ddl: false
    properties:
      hibernate:
        default_schema: whitepappers
  datasource:
    url: jdbc:postgresql://localhost:5432/whitepappers
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      maximumPoolSize: 80
      schema: whitepappers

  flyway:
    schemas: whitepappers
    locations: classpath:/db/migration, classpath:/db/local
    out-of-order: true

jobs:
  enabled: false

audit:
  enabled: true
